### ISSUE TITLE
Assert statement used outside of tests BAN-B101

### ISSUE THREAD

**Issue by kgashok** [Pavithratrdev/first-issues#1]
From https://deepsource.io/gh/Pavithratrdev/first-issues/issue/BAN-B101/occurrences

Need to ignore Assert statements in test files as security issue

Usage of assert statement in application logic is discouraged. assert is removed with compiling to optimised byte code (python -o producing *.pyo files). Consider raising an exception instead. Ideally, assert statement should be used only in tests.

Tip: Make sure test_patterns are defined in .deepsource.toml to avoid false-positives - https://deepsource.io/docs/config/deepsource-toml.html#test-patterns

**Comment by kgashok** [comment]
@Pavithratrdev From https://deepsource.io/docs/concepts/#test_patterns 

```
test_patterns = [
  "tests/**",
  "test_*.py"
]
```

**Comment by kgashok** [comment]
@Pavithratrdev Need to confirm if the false-positive issues go away.

**Comment by kgashok** [comment]
Not working - not sure where to place the test_patterns array.

**Comment by Pavithratrdev** [comment]
Sir, Will check on this

**Comment by kgashok** [comment]
Resolved now due to proper edit of deepsource.toml
